FROM debian:12.5

RUN  apt-get update
RUN  apt-get install -y cmake git g++ zlib1g-dev
RUN apt install -y wget software-properties-common gnupg
RUN apt install -y lsb-release
RUN wget https://apt.llvm.org/llvm.sh
RUN chmod +x llvm.sh
RUN ./llvm.sh 14 all
RUN apt install clang-format
